//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : 
//"                      
//"                      
//" Script Author      : Nacho
//" Script Date        : Sat Feb 13 20:55:31 2016
//" Generated By       : LoadRunner Recorder (Build: 1096)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

function vuser_init()
{
	return 0;
}

